#!/usr/bin/env node
/**
 * Interim web-only i18n generator (ADR 0016 deviation, until tools/i18n-gen exists).
 *
 * Reads shared/i18n/<locale>.json and writes i18next resources to
 * src/generated/i18n/<locale>.json (flat `{ key: message }`) plus src/generated/i18n/index.ts.
 * The output is build output: gitignored (`/apps/web/src/generated/`), never hand-edited.
 *
 * Checks (a subset of what tools/i18n-gen will do):
 * - every message parses as ICU MessageFormat;
 * - en.json entries have `{ message, description }`;
 * - other locales only use keys that exist in en.json.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { IntlMessageFormat } from 'intl-messageformat';

const here = dirname(fileURLToPath(import.meta.url));
const sourceDir = resolve(here, '../../../shared/i18n');
const outDir = resolve(here, '../src/generated/i18n');

const errors = [];
const locales = readdirSync(sourceDir)
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.slice(0, -'.json'.length))
  .sort();

if (!locales.includes('en')) {
  console.error(`gen-i18n: ${sourceDir}/en.json is missing`);
  process.exit(1);
}

function load(locale) {
  return JSON.parse(readFileSync(join(sourceDir, `${locale}.json`), 'utf8'));
}

function toMessages(locale, source) {
  const out = {};
  for (const [key, value] of Object.entries(source)) {
    let message;
    if (locale === 'en') {
      if (typeof value !== 'object' || value === null || typeof value.message !== 'string') {
        errors.push(`${locale}: "${key}" must be { "message": string, "description": string }`);
        continue;
      }
      if (typeof value.description !== 'string' || value.description.trim() === '') {
        errors.push(`${locale}: "${key}" needs a description for translators`);
      }
      message = value.message;
    } else {
      message = typeof value === 'string' ? value : value?.message;
      if (typeof message !== 'string') {
        errors.push(`${locale}: "${key}" must be a string`);
        continue;
      }
    }
    try {
      new IntlMessageFormat(message, locale === 'kea' ? 'pt' : locale);
    } catch (e) {
      errors.push(`${locale}: "${key}" is not valid ICU: ${e instanceof Error ? e.message : e}`);
    }
    out[key] = message;
  }
  return out;
}

const en = toMessages('en', load('en'));
const resources = { en };
for (const locale of locales) {
  if (locale === 'en') continue;
  const messages = toMessages(locale, load(locale));
  for (const key of Object.keys(messages)) {
    if (!(key in en)) errors.push(`${locale}: unknown key "${key}" (not in en.json)`);
  }
  resources[locale] = messages;
}

if (errors.length > 0) {
  console.error(`gen-i18n: ${errors.length} error(s)\n  ${errors.join('\n  ')}`);
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
for (const [locale, messages] of Object.entries(resources)) {
  writeFileSync(join(outDir, `${locale}.json`), `${JSON.stringify(messages, null, 2)}\n`);
}
const imports = locales.map((l) => `import ${l} from './${l}.json';`).join('\n');
writeFileSync(
  join(outDir, 'index.ts'),
  `// GENERATED by apps/web/scripts/gen-i18n.mjs from shared/i18n. Do not edit.\n${imports}\n\n` +
    `export const resources = { ${locales.map((l) => `${l}: { translation: ${l} }`).join(', ')} };\n` +
    `export const locales = ${JSON.stringify(locales)} as const;\n` +
    `export type MessageKey = keyof typeof en;\n`,
);
console.log(
  `gen-i18n: ${locales.join(', ')} (${Object.keys(en).length} keys) -> src/generated/i18n`,
);
