import i18next from 'i18next';
import ICU from 'i18next-icu';
import { initReactI18next } from 'react-i18next';

// Generated from shared/i18n/*.json by scripts/gen-i18n.mjs (run by dev/build/test/typecheck).
// Interim stand-in for tools/i18n-gen (ADR 0016). Never edit src/generated by hand.
import { locales, resources } from '../generated/i18n';

export const SUPPORTED_LOCALES: readonly string[] = locales;

void i18next
  .use(ICU)
  .use(initReactI18next)
  .init({
    lng: 'en',
    fallbackLng: 'en',
    supportedLngs: [...locales],
    // Keys are flat and dotted (`game.captured`): don't treat dots or colons as separators.
    keySeparator: false,
    nsSeparator: false,
    resources,
    interpolation: { escapeValue: false },
    returnNull: false,
    initAsync: false,
  });

export default i18next;
